### ISSUE TITLE
Support for encryption keys?

### ISSUE THREAD

**Issue by AdmiralStipe** [aviborg/esp-smart-meter#11]
The code seems to be generally working on my meter (Iskraemeco AM550 in Slovenia, RJ12 port) with minor adaptations (baudrate 38400), but I have problems reading the data as my meter's P1 port it's encrypted. I have all decryption keys for my meter available (unicast, broadcast and auth), but nowhere to put them in the code. Is the use of encrypted data and decryption even supported?

**Comment by aviborg** [comment]
Sorry, but support for encryption is not implemented. I would be happy to accept a pull request, or if i get the time I could do it. Do you have any specs on the encryption scheme?

**Comment by AdmiralStipe** [comment]
Sorry, I'm total noob in this regard. Maybe [this](https://icube.ch/Security/ciphered-context-GMAC-example.html) or [this](https://github.com/saghonfly/shrdzm/blob/master/code/SHRDZMDevice/Device_IM350.cpp) can help you? I tried the second one, but it's also not working for me, presumably because of incorrect baudrate (115200).

**Comment by AdmiralStipe** [comment]
Good news, Erich implemented it [in here](https://github.com/saghonfly/shrdzm/blob/master/code/SHRDZMDevice/Device_IM350.cpp), if it's of any help to you.
