### ISSUE TITLE
Current flowing towards the data line

### ISSUE THREAD

**Issue by dimme** [aviborg/esp-smart-meter#12]
Hello there.

You have a 1kΩ resistor between +5V and the data line in your design.

According to the [P1 Companion Standard](https://www.netbeheernederland.nl/_upload/Files/Slimme_meter_15_a727fce1f1.pdf), the maximum current flowing towards the data line must not exceed 5 mA.

That means the resistor must be at least `5V / 5mA = 1kΩ` in a perfect world. Given typical tolerance values, I have increased mine to 10kΩ to be on the safe side.

There is still enough [base current](https://www.petervis.com/GCSE_Design_and_Technology_Electronic_Products/transistor_base_resistor_calculator/transistor_base_resistor_calculator.html) for hard saturation in the BJT.

Here is my design as a reference:

![image](https://user-images.githubusercontent.com/501045/146302689-bebbe464-0493-4ebe-9ead-ff8501e243e1.png)

Btw, I'm just a hobbyist. If I'm talking bullshit, feel free to put me in my place 😃

**Comment by aviborg** [comment]
You're probably correct. I'll add that to the Readme in due time.
