### ISSUE TITLE
Error reading input from meter

### ISSUE THREAD

**Issue by flighttronics** [aviborg/esp-smart-meter#13]
/LGF5E360

0-0:1.0.0(220930153230W)
1-0:1.8.0(00008372.794*kWh)
1-0:2.8.0(00000000.000*kWh)
1-0:3.8.0(00000096.645*kVArh)
1-0:4.8.0(00003381.975*kVArh)
1-0:1.7.0(0000.565*kW)
1-0:2.7.0(0000.000*kW)
1-0:3.7.0(0000.000*kVAr)
1-0:4.7.0(0000.357*kVAr)
1-0:21.7.0(0000.396*kW)
1-0:22.7.0(0000.000*kW)
1-0:41.7.0(0000.059*kW)
1-0:42.7.0(0000.000*kW)
1-0:61.7.0(0000.110*kW)
1-0:62.7.0(0000.000*kW)
1-0:23.7.0(0000.000*kVAr)
1-0:24.7.0(0000.180*kVAr)
1-0:43.7.0(0000.000*kVAr)
1-0:44.7.0(0000.035*kVAr)
1-0:63.7.0(0000.000*kVAr)
1-0:64.7.0(0000.142*kVAr)
1-0:32.7.0(230.8*V)
1-0:52.7.0(231.5*V)
1-0:72.7.0(231.5*V)
1-0:31.7.0(001.8*A)
1-0:51.7.0(000.2*A)
1-0:71.7.0(000.7*A)
!5EFB

--- Start 9019232 ---
0x2d, 0x30, 0x3a, 0x32, 0x34, 0x2e, 0x37, 0x2e, 0x30, 0x28, 0x30, 0x30, 0x30, 0x30, 0x2e, 0x31, 
0x30, 0x32, 0x2a, 0x6b, 0x56, 0x41, 0x72, 0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x34, 0x33, 
0x2e, 0x37, 0x2e, 0x30, 0x28, 0x30, 0x30, 0x30, 0x30, 0x2e, 0x30, 0x30, 0x30, 0x2a, 0x6b, 0x56, 
0x41, 0x72, 0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x34, 0x34, 0x2e, 0x37, 0x2e, 0x30, 0x28, 
0x30, 0x30, 0x30, 0x30, 0x2e, 0x30, 0x34, 0x33, 0x2a, 0x6b, 0x56, 0x41, 0x72, 0x29, 0x0d, 0x0a, 
0x31, 0x2d, 0x30, 0x3a, 0x36, 0x33, 0x2e, 0x37, 0x2e, 0x30, 0x28, 0x30, 0x30, 0x30, 0x30, 0x2e, 
0x30, 0x30, 0x30, 0x2a, 0x6b, 0x56, 0x41, 0x72, 0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x36, 
0x34, 0x2e, 0x37, 0x2e, 0x30, 0x28, 0x30, 0x30, 0x30, 0x30, 0x2e, 0x31, 0x36, 0x31, 0x2a, 0x6b, 
0x56, 0x41, 0x72, 0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x33, 0x32, 0x2e, 0x37, 0x2e, 0x30, 
0x28, 0x32, 0x32, 0x32, 0x2e, 0x39, 0x2a, 0x56, 0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x35, 
0x32, 0x2e, 0x37, 0x2e, 0x30, 0x28, 0x32, 0x32, 0x39, 0x2e, 0x30, 0x2a, 0x56, 0x29, 0x0d, 0x0a, 
0x31, 0x2d, 0x30, 0x3a, 0x37, 0x32, 0x2e, 0x37, 0x2e, 0x30, 0x28, 0x32, 0x33, 0x31, 0x2e, 0x33, 
0x2a, 0x56, 0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x33, 0x31, 0x2e, 0x37, 0x2e, 0x30, 0x28, 
0x30, 0x31, 0x30, 0x2e, 0x34, 0x2a, 0x41, 0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x35, 0x31, 
0x2e, 0x37, 0x2e, 0x30, 0x28, 0x30, 0x30, 0x30, 0x2e, 0x35, 0x2a, 0x41, 0x29, 0x0d, 0x0a, 0x31, 
0x2d, 0x30, 0x3a, 0x37, 0x31, 0x2e, 0x37, 0x2e, 0x30, 0x28, 0x30, 0x30, 0x30, 0x2e, 0x38, 0x2a, 
0x41, 0x29, 0x0d, 0x0a, 0x21, 0x41, 0x43, 0x46, 0x39, 0x0d, 0x0a, 
---  End  ---

**Comment by aviborg** [comment]
This seems correct.

What do you get from 
emeter/data.json
