### ISSUE TITLE
What does everything mean on the webserver?

### ISSUE THREAD

**Issue by alexbergsland** [aviborg/esp-smart-meter#6]
Not really an issue but more of a question.
I followed your guide and made the reader and connected it to my Aidon 6442SE.
I get a lot of readings but they don't make any sense, do you know what they all mean?
There are for example:
0100200700FF: 2325 : -1 : V
0100340700FF: 2372 : -1 : V
0100480700FF: 2364 : -1 : V
Which looks like voltage but multiplied by 10, is that right?

I see 26 lines with data.

I use Domoticz and I could just use the json and pick out the relevant parts and send them to dummy things in Domoticz, like a P1 meter or something like that. Or do you know of any complete solution that could use this data right away?

A list on the wiki of what it all is if you know would be great, I can write it if you give me the details :)

**Comment by alexbergsland** [comment]
Oh, I see now that there is even a V after those rows.
And the same thing I guess on the data you described in the wiki, amps are need dividing by10 (or missing a comma).

**Comment by aviborg** [comment]
When I started this projekt I learned that different meters send out data on unique formats. This project aim to be generic and convert any data format (based on OBIS codes) to json format which is a standard format readable by most applications.

Any adaption is the to be made your Home Server such as Domoticz. You're welcome to write a guide how to as I only have OpenHAB and Home Assistant for the moment.

My first attempt was a python project in another repo, take a look how to interpret the raw data here from the Aidon meter here:
[https://github.com/aviborg/swedishP1/blob/main/data/aidon20201108_112447.txt](url)

The first number (0100200700FF) in your example is the hexadecimal OBIS code which is specified in an ISO standard, but you can find the meaning in most manuals: 
[https://www.tekniskaverken.se/privat/elnat/matning-av-din-elanvandning/din-elmatare/](url)
[https://github.com/aviborg/esp-smart-meter/blob/master/docs/aidonfd-rj12-han-interface-se-v13a.pdf](url)

The second value is the voltage as specified by the OBIS code.

The third is a exponent of 10: 10<sup>-1</sup> meaning the value should be divided by 10.

Fourth is unit.

**Comment by alexbergsland** [comment]
I found something to translate the OBIS hex, which I could not do on my own:
https://www.gurux.fi/GuruxDLMSTranslator
