### ISSUE TITLE
Functionality with Landis o Gyr E360

### ISSUE THREAD

**Issue by aeiurf** [aviborg/esp-smart-meter#7]
Has anyone successfully used this with a Landis o Gyr E360?
I only receive data sporadically, CRC seems to always be correct though. 
The problem seems to be that i’m missing some of the data.

From log.txt:

--- Start 374880 ---
0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x35, 0x31, 0x2e, 0x37, 0x2e, 0x30, 0x28, 0x30, 0x30, 
0x30, 0x2e, 0x30, 0x2a, 0x41, 0x29, 0x0d, 0x0a, 0x31, 0x2d, 0x30, 0x3a, 0x37, 0x31, 0x2e, 0x37, 
0x2e, 0x30, 0x28, 0x30, 0x30, 0x30, 0x2e, 0x30, 0x2a, 0x41, 0x29, 0x0d, 0x0a, 0x21, 0x38, 0x42, 
0x37, 0x32, 0x0d, 0x0a, 
---  End  ---

**Comment by aviborg** [comment]
Landis&Gyr has some bugs, see this thread: https://www.byggahus.se/forum/threads/elmaetare-h1-port-p1-port-han-port-manga-namn-verkar-florera.384608/page-4 

It might be that Landis&Gyr send data in chunks with some delay and my implementation is configured to start process the data X ms after data was received, 

You may want to try this implementation: https://github.com/psvanstrom/esphome-p1reader/ Let us know if this implementation works.
