### ISSUE TITLE
Functionality with Kamstrup DK-8660 electrical meter

### ISSUE THREAD

**Issue by Bigert** [aviborg/esp-smart-meter#8]
I was going to start with a similar project as my first project in many years, so I started with a test connection with Arduino to see what I got out of the serial port. I use a HAN port with RJ12 and inverts the signal.

There is a lot of conflicting information about port speed, but I got 2400 baud to work. I expected a list corresponding to your example list, but got the following according to appendix image (char dump) and list below (int dump).

Am I lost or may the power network owner have set the wrong parameters for my electrical meter?
It's a very small power network owner and I am the first customer with RJ12 adapter?

126
![Kamstrup](https://user-images.githubusercontent.com/16431285/119898968-cba0ec80-bf42-11eb-80fd-61296e097c07.jpg)

160
226
43
33
19
35
154
230
231
0
15
0
0
0
0
12
7
229
5
27
4
14
46
10
255
128
0
128
2
25
10
14
75
97
109
115
116
114
117
112
95
86
48
48
48
49
9
6
1
1
0
0
5
255
10
16
53
55
48
54
53
54
55
51
51
50
54
48
56
53
50
51
9
6
1
1
96
1
1
255
10
18
54
56
52
49
49
51
56
65
78
50
52
53
49
48
49
48
57
48
9
6
1
1
6
123
1
255
0
1
7
6
0
6
4
255
0
1
0
0
6
7
0
9
71
6
35
1
255
9
52
18
6
7
18
239
126
160
226
43
33
19
35
154
230
231
0
15
0
0
0
0
12
7
229
5
27
4
14
46
20
255
128
0
128
2
25
10
14
75
97
109
115
116
114
117
112
95
86
48
48
48
49
9
6
1
1
0
0
5
255
10
16
53
55
48
54
53
54
55
51
51
50
54
48
56
53
50
51
9
6
1
1
96
1
1
255
10
18
54
56
52
49
49
51
56
65
78
50
52
53
49
48
49
48
57
48
9
6
1
1
6
125
1
255
0
1
7
6
0
6
4
255
0
1
0
0
6
7
0
9
71
6
36
1
255
9
1
255
9
72
18
190
126
160
226
43
33
19
35
154
230
231
0
15
0
0
0
0
12
7
229
5
27
4
14
46
30
255
128
0
128
2
25
10
14
75
97
109
115
116
114
117
112
95
86
48
48
48
49
9
6
1
1
0
0
5
255
10
16
53
55
48
54
53
54
55
51
51
50
54
48
56
53
50
51
9
6
1
1
96
1
1
255
10
18
54
56
52
49
49
51
56
65
78
50
52
53
49
48
49
48
57
48
9
6
1
1
6
120
1
255
0
1
7
6
0
6
4
255
0
1
0
0
6
7
0
9
71
6
35
1
255
9
52
18
9
72
18
152
126
160
226
43
33
19
35
154
230
231
0
15
0
0
0
0
12
7
229
5
27
4
14
46
40
255
128
0
128
2
25
10
14

**Comment by aviborg** [comment]
It seems you have A-XDR and it reads out correct. As you have to use 2400 baud you might have an older version but I can tell that the initial data is correct as it starts with 126 (0x7e).
Here is an explanation of the meaning of it: https://github.com/aviborg/swedishP1/blob/main/data/aidon20201108_112447.txt your dump seems to be very similar if you convert it to hex.
If you use my ESP-code what does it show at http://emeter/data.json ?

**Comment by Bigert** [comment]
Thanks so much for your help. Really appreciate it. 
Then I understand better how the information from the meter is intended.
Then I can try the next step of testing your code and we will see what results it gives in data.json.

**Comment by aviborg** [comment]
yw
